version: "3.9"
services:
  web:
    build: .
    depends_on: mongo
    ports:
      - "5000:5000"
    networks:
      - app-network
  mongo:
    image: "mongo"
    volumes:
      - data-volume:/data/db
    port:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
